[package]
name = "rust-tdlib"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Q <qalexx@gmail.com>"]

[dependencies]
libc = "0.2.148"
log = "0.4.20"

[dev-dependencies]
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
